name: CFB Games (Prefill - Full Week)

on:
  workflow_dispatch:

jobs:
  prefill:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Starting CFB prefill…"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i axios googleapis

      - name: Prefill week (CFB)
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          LEAGUE: college-football
          TAB_NAME: CFB
          RUN_SCOPE: week
        run: node orchestrator.mjs

      - name: Complete job
        run: echo "Done."
