name: CFB Halftime Checker

on:
  workflow_dispatch:
  schedule:
    # Thu & Fri nights often have CFB; Saturdays all day
    - cron: "*/20 22-23 * * 4,5"   # Thu/Fri 6–7:59 PM ET (22–23 UTC)
    - cron: "*/20 0-5 * * 5,6"     # Thu/Fri 8 PM–1:59 AM ET (overnight windows)
    - cron: "*/20 14-23 * * 6"     # Sat 10 AM–7:59 PM ET
    - cron: "*/20 0-4 * * 0"       # Sat late games spill into Sun 8 PM–12:59 AM ET

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      LEAGUE: college-football
      TAB_NAME: CFB
      RUN_SCOPE: today
      MAX_RUNTIME_MIN: "90"       # each wake may sleep once, up to this cap
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 22, cache: npm }
      - run: npm ci || npm install
      - run: npx playwright install --with-deps chromium
      - run: node halftime-checker.mjs
