name: CFB Halftime Checker

on:
  workflow_dispatch:
  schedule:
    # Thu/Fri night CFB windows
    - cron: "*/20 22-23 * * 4,5"   # 6–7:59 PM ET (22–23 UTC)
    - cron: "*/20 0-5 * * 5,6"     # 8 PM–1:59 AM ET
    # Saturday all-day + late spillover
    - cron: "*/20 14-23 * * 6"     # Sat 10 AM–7:59 PM ET
    - cron: "*/20 0-4 * * 0"       # Sat late into Sun 8 PM–12:59 AM ET

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      LEAGUE: college-football
      TAB_NAME: CFB
      RUN_SCOPE: today
      MAX_RUNTIME_MIN: "90"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install npm deps
        run: npm ci || npm install

      - name: Install Playwright (Chromium)
        run: npx playwright install --with-deps chromium

      - name: Run halftime checker
        run: node halftime-checker.mjs
