name: CFB Halftime Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "*/20 22-23 * * 4,5"
    - cron: "*/20 0-5 * * 5,6"
    - cron: "*/20 14-23 * * 6"
    - cron: "*/20 0-4 * * 0"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      LEAGUE: college-football
      TAB_NAME: CFB
      RUN_SCOPE: today
      MAX_RUNTIME_MIN: "90"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: npm install

      - name: Install Playwright (Chromium)
        run: npx playwright install --with-deps chromium

      - name: Run halftime checker
        run: node halftime-checker.mjs
