name: CFB Games (Prefill - Full Week)

on:
  schedule:
    # Morning ET and early afternoon passes to catch full slates
    - cron: "15 11 * * 4,5,6"   # Thu/Fri/Sat 7:15 AM ET
    - cron: "15 15 * * 6"       # Sat 11:15 AM ET
  workflow_dispatch:

jobs:
  prefill:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: |
          npm i googleapis playwright

      - name: Prefill week (CFB)
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          LEAGUE: college-football
          TAB_NAME: CFB
          RUN_SCOPE: week             # 👈 pull the full upcoming week
          ADAPTIVE_HALFTIME: "0"      # 👈 disable halftime/sleep behavior for prefill
        run: node orchestrator.mjs
