name: CFB Games (Prefill)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * 2"  # Tuesdays 10:00 AM ET (14:00 UTC)

jobs:
  prefill:
    runs-on: ubuntu-latest
    env:
      GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      LEAGUE: college-football
      TAB_NAME: CFB
      RUN_SCOPE: week            # pull a full week
      ADAPTIVE_HALFTIME: "0"     # <— disable adaptive sleep
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm install
      # No Playwright here
      - run: node orchestrator.mjs
