name: CFB Games (Prefill)

on:
  workflow_dispatch:
    inputs:
      run_scope:
        description: "Scope (today | week)"
        required: false
        default: "week"
      tab_name:
        description: "Sheet tab to write"
        required: false
        default: "CFB"

jobs:
  prefill:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Prefill CFB games
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          LEAGUE: college-football
          TAB_NAME: ${{ github.event.inputs.tab_name || 'CFB' }}
          RUN_SCOPE: ${{ github.event.inputs.run_scope || 'week' }}
        run: node live-game.mjs
