name: CFB Halftime Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "*/20 22-23 * * 4,5"  # Thu/Fri 6–7:59 PM ET
    - cron: "*/20 0-5 * * 5,6"    # Fri/Sat overnight
    - cron: "*/20 14-23 * * 6"    # Sat 10 AM–7:59 PM ET
    - cron: "*/20 0-4 * * 0"      # Late Sat -> early Sun

concurrency:
  group: cfb-halftime-checker
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    env:
      GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      LEAGUE: college-football
      TAB_NAME: CFB
      RUN_SCOPE: today
      MAX_RUNTIME_MIN: "90"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node (with cache)
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install deps
        run: npm ci --omit=dev

      - name: Run halftime checker
        run: node halftime-checker.mjs
