name: CFB Halftime (Daily timed per game)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"   # every hour, UTC

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      games: ${{ steps.collect.outputs.games }}
    steps:
      - name: Collect today’s CFB games (kickoff + 60m)
        id: collect
        run: |
          set -euo pipefail
          # ESPN "today" in UTC; also collect ET "today" to cross midnight edges
          ET_TZ="America/New_York"
          today_utc="$(date -u +%Y%m%d)"
          et_today="$(TZ=$ET_TZ date +%Y%m%d)"

          fetch() { curl -sS "https://site.api.espn.com/apis/site/v2/sports/football/college-football/scoreboard?dates=$1&groups=80&limit=300"; }

          tmp="$(mktemp)"
          { fetch "$today_utc"; fetch "$et_today"; } | jq -s '
            [.[].events[]?] | unique_by(.id)
          ' > "$tmp"

          now_ts=$(date -u +%s)
          # Build per-game targets; limit to the next 6h to stay under job timeout
          jq -r --argjson now "$now_ts" '
            [ .[]
              | { id: .id
                , kickoff: .date
                , run_at: ( ((.date | fromdateiso8601) + (60*60)) | todateiso8601 )  # +60m
                , delay:   ( ((.date | fromdateiso8601) + (60*60)) - $now )
                }
              | select(.delay >= 0 and .delay <= (6*60*60))
            ]
          ' "$tmp" | jq -c '.' | sed '1!b;s/^/games=/' >> "$GITHUB_OUTPUT"

  per-game:
    needs: build-matrix
    if: ${{ steps.build-matrix.outputs.games != '' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.build-matrix.outputs.games) }}
    concurrency:
      group: cfb-halftime-${{ matrix.include.id }}
      cancel-in-progress: false
    env:
      GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      TAB_NAME: CFB
      MAX_TOTAL_MIN: "200"              # safety cap per game
      TARGET_GAME_ID: ${{ matrix.include.id }}
    steps:
      - uses: actions/checkout@v4

      - name: Sleep until kickoff+60 for this game
        shell: bash
        run: |
          set -euo pipefail
          target_iso='${{ matrix.include.run_at }}'
          target_ts=$(date -u -d "$target_iso" +%s)
          now_ts=$(date -u +%s)
          wait=$(( target_ts - now_ts ))
          if [ $wait -le 0 ]; then
            echo "Time reached; continuing immediately."
          else
            echo "Sleeping $wait seconds until $target_iso (UTC)…"
            sleep $wait
          fi

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Install Playwright (Chromium)
        run: npx playwright install --with-deps chromium

      - name: Run single-game halftime watcher
        run: node ./cfb-halftime-single.mjs
