name: Football (Prefill + Finals + Live)

on:
  workflow_dispatch:
    inputs:
      league:
        description: "Which league(s) to run"
        type: choice
        options:
          - both
          - nfl
          - college-football
        default: both
      run_mode:
        description: "Which phase to run"
        type: choice
        options:
          - all
          - prefill
          - finals
          - live
        default: all
      game_ids:
        description: "Comma-separated Game IDs (optional)"
        required: false
        default: ""

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - league: nfl
            tab: NFL
          - league: college-football
            tab: CFB

    steps:
      - name: Conditional skip (league filter)
        if: ${{ !(github.event.inputs.league == 'both' || github.event.inputs.league == matrix.league) }}
        run: |
          echo "Skipping matrix.league=${{ matrix.league }} because workflow input league=${{ github.event.inputs.league }}"
          exit 0

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json', 'package.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Install deps
        run: |
          npm ci || npm i
          npm ls axios googleapis >/dev/null 2>&1 || npm i axios googleapis

      - name: Run Football.mjs
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          LEAGUE: ${{ matrix.league }}
          TAB_NAME: ${{ matrix.tab }}
          RUN_SCOPE: week
          RUN_MODE: ${{ github.event.inputs.run_mode }}
          GAME_IDS: ${{ github.event.inputs.game_ids }}
          GHA_JSON: "1"
        run: node Football.mjs
