Football.yml
name: Football (Prefill + Finals + Live)

on:
  workflow_dispatch:
    inputs:
      league:
        description: "Which league(s) to run"
        type: choice
        options:
          - both
          - nfl
          - college-football
        default: both
      run_mode:
        description: "Which phase to run"
        type: choice
        options:
          - all
          - prefill
          - finals
          - live
        default: all
      game_ids:
        description: "Comma-separated Game IDs (optional)"
        required: false
        default: ""
