name: Halftime (CFB)

on:
  schedule:
    # Saturday early games (10 AM–6 PM ET)
    - cron: "*/20 14-22 * * 6"
    # Saturday night games (6 PM–2 AM ET)
    - cron: "*/20 22-6 * * 6"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      LEAGUE: college-football
      TAB_NAME: CFB
      RUN_SCOPE: today
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 22 }
      - run: npm install
      - run: npx playwright install --with-deps chromium
      - run: node orchestrator.mjs
