name: Live Manual Check

on:
  workflow_dispatch:
    inputs:
      league:
        description: "League to check (nfl or college-football)"
        required: true
        default: "nfl"
      game_id:
        description: "Specific ESPN Game ID to force update (optional)"
        required: false
        default: ""

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm i axios googleapis

      - name: Run manual live update
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          LEAGUE: ${{ github.event.inputs.league }}
          TAB_NAME: ${{ fromJson('{"nfl":"NFL","college-football":"CFB"}')[github.event.inputs.league] }}
          GAME_ID: ${{ github.event.inputs.game_id }}
        run: node live-game.mjs
