name: 🏈 NFL Halftime (Daily Morning Schedule)

on:
  schedule:
    # 9:00 AM Eastern (13:00 UTC) daily
    - cron: "0 13 * * *"
  workflow_dispatch:  # optional manual trigger

jobs:
  nfl-halftime-daily:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run Orchestrator (Pregame + Halftime + Live odds write)
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          LEAGUE: nfl
          TAB_NAME: NFL
          RUN_SCOPE: week
          ADAPTIVE_HALFTIME: "1"
          HALFTIME_EARLY_MIN: "60"
          HALFTIME_LATE_MIN: "90"
        run: node orchestrator.mjs
