name: NFL Halftime Checker

on:
  workflow_dispatch:
  schedule:
    # --- Morning pre-check every day (9–10 AM ET). Use both 13:00/14:00 UTC to straddle DST ---
    - cron: "0 13 * * *"
    - cron: "0 14 * * *"

    # --- Daily evening/night windows (covers TNF/MNF/SNF & any odd nights) ---
    - cron: "*/20 22-23 * * *"   # 6–7:59 PM ET
    - cron: "*/20 0-6 * * *"     # 8 PM–2:59 AM ET

    # --- Sunday daytime + SNF spill into early Monday ---
    - cron: "*/20 14-23 * * 0"   # Sun 10 AM–7:59 PM ET
    - cron: "*/20 0-4 * * 1"     # SNF late spill -> Mon 12:59 AM ET

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      LEAGUE: nfl
      TAB_NAME: NFL
      RUN_SCOPE: today
      MAX_RUNTIME_MIN: "90"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install deps (from lockfile)
        run: npm ci

      - name: Run halftime checker
        run: node halftime-checker.mjs
