name: Run NFL EPA Script

on:
  workflow_dispatch:    # allows manual run
  schedule:
    - cron: "0 * * * *" # runs every hour (UTC) — adjust later when linked to halftime detector

jobs:
  run-epa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r nfl-epa-sheets/requirements.txt

      - name: Run NFL EPA
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }}
          SEASONS: "2025"
          LEAGUE: "NFL"
          START_CELL: "Q2"
          SHEET_TAB_NFL: "NFL"
        run: |
          python nfl-epa-sheets/NFL_EPA.py
