name: NFL Halftime Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 16-23 * * 0,1,4"  # Sun/Mon/Thu 12–7:59 PM ET
    - cron: "*/15 0-3 * * 1,2,5"    # Sun/Mon/Thu 8 PM–10:59 PM ET spill into next UTC day

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      LEAGUE: nfl
      TAB_NAME: NFL
      RUN_SCOPE: today
      MAX_RUNTIME_MIN: "90"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 22, cache: npm }
      - run: npm ci || npm install
      - run: npx playwright install --with-deps chromium
      - run: node halftime-checker.mjs
