name: NFL Halftime Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 16-23 * * 0,1,4"  # Sun/Mon/Thu prime windows
    - cron: "*/15 0-3 * * 1,2,5"    # late spillover into next day

concurrency:
  group: nfl-halftime-checker
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    env:
      GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      LEAGUE: nfl
      TAB_NAME: NFL
      RUN_SCOPE: today
      MAX_RUNTIME_MIN: "90"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node (with cache)
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install deps
        run: npm ci --omit=dev

      - name: Run halftime checker
        run: node halftime-checker.mjs
