name: NFL Halftime

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 16-23 * * 0,1,4"  # Sun/Mon/Thu, every 15 min, 12:00–19:59 ET (16–23 UTC)

jobs:
  halftime:
    runs-on: ubuntu-latest
    env:
      GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      LEAGUE: nfl
      TAB_NAME: NFL
      RUN_SCOPE: today
      MAX_RUNTIME_MIN: "120"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 22, cache: "npm" }
      - run: npm install
      - run: npx playwright install --with-deps chromium
      - run: node halftime-checker.mjs
