name: NFL Halftime Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *" # Runs every day at 8 AM ET

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      SHEET_ID: ${{ secrets.SHEET_ID }}
      GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run halftime checker
        run: |
          echo "Running halftime-checker.mjs..."
          node halftime-checker.mjs

      - name: Trigger EPA writer
        if: success()
        uses: ./.github/workflows/NFL-epa.yml
        with:
          league: "nfl"
          seasons: "2025"
