name: NFL Halftime Checker

on:
  schedule:
    # Runs every day at 10 AM ET to wake up and check games
    - cron: "0 14 * * *"   # 10:00 AM ET (14 UTC)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run halftime checker
        id: halftime
        run: |
          echo "Running halftime-checker.mjs..."
          node halftime-checker.mjs > output.log
          cat output.log

          # Detect halftime flag (you can modify this logic as needed)
          if grep -q "adaptive candidates" output.log; then
            echo "halftime_found=true" >> $GITHUB_OUTPUT
          else
            echo "halftime_found=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger EPA writer
        if: steps.halftime.outputs.halftime_found == 'true'
        uses: ./.github/workflows/NFL_epa.yml
        with:
          league: "nfl"
          seasons: "2025"
