name: NFL Games (Prefill)

on:
  workflow_dispatch:

jobs:
  prefill:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Starting NFL prefill…"

      - name: Run actions/checkout@v4
        uses: actions/checkout@v4

      - name: Run actions/setup-node@v4
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm i axios googleapis

      - name: Run node orchestrator.mjs
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          LEAGUE: nfl
          TAB_NAME: NFL
          RUN_SCOPE: week
        run: node orchestrator.mjs
