name: 🏈 NFL EPA Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 2"  # Every Tuesday at 3:00 AM UTC (after MNF)
  push:
    paths:
      - "NFL_EPA.py"

jobs:
  run-epa:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show repo tree (debug)
        run: |
          echo "Repo structure:"
          ls -R

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Python and dependencies
        run: |
          python --version
          pip list

      - name: Run NFL EPA Script
        env:
          SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GCP_SA_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          SHEET_TAB_NFL: "NFL"
          START_CELL: "Q2"
          SEASON: "2025"
          LEAGUE: "NFL"
        run: |
          echo "Running NFL_EPA.py..."
          python NFL_EPA.py
