name: NFL EPA Writer

on:
  workflow_call:
    inputs:
      league:
        required: true
        type: string
      seasons:
        required: true
        type: string
      python_version:
        required: false
        type: string
        default: '3.11'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SHEET_ID: ${{ secrets.SHEET_ID }}
      LEAGUE: ${{ inputs.league }}
      SEASONS: ${{ inputs.seasons }}
      GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python C:\Users\kaylu\OneDrive\Desktop\Coding\nfl-epa-sheets\NFL_EPA.py
