name: Orchestrator Finals (sweeper)

on:
  schedule:
    - cron: '*/15 17-23 * * *'  # 1 PM–11 PM UTC (9 AM–7 PM ET)
    - cron: '*/15 0-2 * * *'    # 12 AM–2 AM UTC (8 PM–10 PM ET)
  workflow_dispatch:

jobs:
  sweep:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        league: [nfl, college-football]
        include:
          - league: nfl
            tab: NFL
          - league: college-football
            tab: CFB

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm i googleapis

      - name: Run orchestrator finals sweep
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          LEAGUE: ${{ matrix.league }}
          TAB_NAME: ${{ matrix.tab }}
          RUN_SCOPE: today
        run: node orchestrator.mjs
