name: Orchestrator

on:
  workflow_dispatch:
    inputs:
      league:
        description: "League to run"
        type: choice
        required: true
        default: both
        options: [both, nfl, college-football]
      game_ids:
        description: "Optional: one or more ESPN game IDs (comma or space separated)"
        required: false
        default: ""

concurrency:
  group: orchestrator-${{ github.run_id }} # allow both jobs to run together per dispatch
  cancel-in-progress: false

env:
  GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
  GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
  TZ: America/New_York
  ADAPTIVE_HALFTIME: "1"   # always on
  GAME_IDS: ${{ inputs.game_ids }}

jobs:
  run-nfl:
    if: ${{ inputs.league == 'both' || inputs.league == 'nfl' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install --no-audit --no-fund
          npx playwright install --with-deps chromium

      - name: Decide RUN_SCOPE (ET)
        run: |
          # 1=Mon .. 5=Fri 6=Sat 7=Sun
          dow=$(date +%u)
          if [ "$dow" -ge 5 ]; then scope=today; else scope=week; fi
          echo "RUN_SCOPE=$scope" >> "$GITHUB_ENV"

      - name: Run orchestrator (NFL)
        env:
          LEAGUE: nfl
        run: node orchestrator.mjs

  run-cfb:
    if: ${{ inputs.league == 'both' || inputs.league == 'college-football' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install --no-audit --no-fund
          npx playwright install --with-deps chromium

      - name: Decide RUN_SCOPE (ET)
        run: |
          dow=$(date +%u)
          if [ "$dow" -ge 5 ]; then scope=today; else scope=week; fi
          echo "RUN_SCOPE=$scope" >> "$GITHUB_ENV"

      - name: Run orchestrator (CFB)
        env:
          LEAGUE: college-football
        run: node orchestrator.mjs
