name: CFB Live (Daily Planner)

on:
  schedule:
    # Every 5 minutes during typical Saturday-day + weekday evenings in UTC
    - cron: "*/5 15-08 * * 6"   # Saturdays 15:00–08:59 UTC
    - cron: "*/5 22-06 * * 1-5" # Weeknights for weekday CFB slates (Mon–Fri 22:00–06:59 UTC)
  workflow_dispatch:

jobs:
  live:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install runtime deps
        run: npm i axios googleapis

      - name: Run live updater (CFB)
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          LEAGUE: "college-football"
          TAB_NAME: "CFB"
        run: node live-game.mjs
