name: CFB Live (Daily Planner)

on:
  schedule:
    # Evening windows (16:00–23:59 UTC)
    - cron: "*/5 16-23 * * 4"   # Thursday
    - cron: "*/5 16-23 * * 5"   # Friday
    - cron: "*/5 16-23 * * 6"   # Saturday
    - cron: "*/5 16-23 * * 0"   # Sunday
    # Early-morning spillover (00:00–06:59 UTC)
    - cron: "*/5 0-6 * * 5"     # Friday early morning
    - cron: "*/5 0-6 * * 6"     # Saturday early morning
    - cron: "*/5 0-6 * * 0"     # Sunday early morning
    - cron: "*/5 0-6 * * 1"     # Monday early morning
  workflow_dispatch:

jobs:
  live:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install runtime deps
        run: npm i axios googleapis

      - name: Run live updater (CFB)
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          LEAGUE: "college-football"
          TAB_NAME: "CFB"
        run: node live-game.mjs
